//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Common.Storage;
using Services.AuthZ.Storage.DataEntities;
using Services.DataContracts;

namespace Services.AuthZ.Storage
{
    /// <summary>
    /// A storage provider for <see cref="IClientApplication"/>
    /// </summary>
    internal partial class ClientApplicationStorageProvider : BaseStorageProvider<IClientApplication, ClientApplicationEntity>
    {
        /// <summary>
        /// Converts the <see cref="ClientApplicationEntity"/> to a DTO of <see cref="IClientApplication"/>
        /// </summary>
        protected override IClientApplication ToDto(ClientApplicationEntity entity)
        {
            return entity.ToDto();
        }

        /// <summary>
        /// Converts the DTO <see cref="IClientApplication"/> to a entity of <see cref="ClientApplicationEntity"/>
        /// </summary>
        protected override ClientApplicationEntity FromDto(IClientApplication contract)
        {
            return ClientApplicationEntity.FromDto(contract);
        }

        /// <summary>
        /// Creates a new identity for the new entity
        /// </summary>
        protected override string CreateIdentity(ClientApplicationEntity entity)
        {
            return Guid.NewGuid().ToString();
        }
    }
}
