//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Services.MessageContracts
{
    /// <summary>
    /// Defines the response for the <see cref="CreateAccessToken"/> request.
    /// </summary>
    [DataContract]
    public partial class CreateAccessTokenResponse
    {
        /// <summary>
        /// Gets or sets the <see cref="ServiceStack.ResponseStatus"/> of the response.
        /// </summary>
        [DataMember]
        public ServiceStack.ResponseStatus ResponseStatus { get; set; }

        /// <summary>
        /// Gets or sets the accesstoken
        /// </summary>
        [DataMember(Name = "access_token")]
        public System.String AccessToken { get; set; }

        /// <summary>
        /// Gets or sets the expiresin
        /// </summary>
        [DataMember(Name = "expires_in")]
        public System.String ExpiresIn { get; set; }

        /// <summary>
        /// Gets or sets the refreshtoken
        /// </summary>
        [DataMember(Name = "refresh_token")]
        public System.String RefreshToken { get; set; }

        /// <summary>
        /// Gets or sets the scope
        /// </summary>
        [DataMember(Name = "scope")]
        public System.String Scope { get; set; }

        /// <summary>
        /// Gets or sets the tokentype
        /// </summary>
        [DataMember(Name = "token_type")]
        public System.String TokenType { get; set; }

    }
}