//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Services.MessageContracts
{
    /// <summary>
    /// Defines the response for the <see cref="ListUserAccounts"/> request.
    /// </summary>
    public partial class ListUserAccountsResponse
    {
        /// <summary>
        /// Gets or sets the <see cref="ServiceStack.ResponseStatus"/> of the response.
        /// </summary>
        public ServiceStack.ResponseStatus ResponseStatus { get; set; }

        /// <summary>
        /// Gets or sets the useraccounts
        /// </summary>
        public List<DataContracts.UserAccount> UserAccounts { get; set; }

    }
}