//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common.Storage;
using Common.Storage.DataEntities;
using Services.DataContracts;

namespace Services.AuthZ.Storage.DataEntities
{
    /// <summary>
    /// An azure storage table context for an <see cref="UserAccount" />.
    /// </summary>
    internal partial class UserAccountEntityStore : InMemoryStoreContext<UserAccountEntity>
    {

    }
}
