//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Net;
using Common.Services;
using Services.AuthZ.Workflow;
using Services.MessageContracts;
using ServiceStack;

namespace Services.AuthZ.Services
{
    /// <summary>
    /// Provides the service endpoint for exposing the 'AccessTokens' resource.
    /// </summary>
    internal partial class AccessTokens : ServiceBase, IAccessTokens
    {
        /// <summary>
        /// Gets or set the <see cref="IAccessTokensManager"/>
        /// </summary>
        public IAccessTokensManager AccessTokensManager { get; set; }

        /// <summary>
        /// Provides the Create request for the 'AccessTokens' resource.
        /// </summary>
        [AddHeader(ContentType = @"application/json")]
        public CreateAccessTokenResponse Post(CreateAccessToken body)
        {
            return ProcessRequest(body, HttpStatusCode.Created, () =>
            {
                var response = this.AccessTokensManager.CreateAccessToken(this.Request, body);
                this.SetLocationHeader(GetCreateAccessTokenResponseId(response));

                return response;
            });
        }

    }
}