//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Services.MessageContracts;

namespace Services.AuthZ.Services
{
    /// <summary>
    /// Defines the service endpoint for exposing the 'AccessTokens' resource.
    /// </summary>
    internal interface IAccessTokens
    {
        /// <summary>
        /// Defines the Create request for the 'AccessTokens' resource.
        /// </summary>
        CreateAccessTokenResponse Post(CreateAccessToken request);

    }
}