//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Services.MessageContracts;

namespace Services.AuthZ.Services
{
    /// <summary>
    /// Defines the service endpoint for exposing the 'ClientApplications' resource.
    /// </summary>
    internal interface IClientApplications
    {
        /// <summary>
        /// Defines the Get request for the 'ClientApplications' resource.
        /// </summary>
        GetClientApplicationResponse Get(GetClientApplication request);

        /// <summary>
        /// Defines the Create request for the 'ClientApplications' resource.
        /// </summary>
        CreateClientApplicationResponse Post(CreateClientApplication request);

        /// <summary>
        /// Defines the Delete request for the 'ClientApplications' resource.
        /// </summary>
        DeleteClientApplicationResponse Delete(DeleteClientApplication request);

    }
}