//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Services.MessageContracts;

namespace Services.AuthZ.Services
{
    /// <summary>
    /// Defines the service endpoint for exposing the 'UserAccounts' resource.
    /// </summary>
    internal interface IUserAccounts
    {
        /// <summary>
        /// Defines the Get request for the 'UserAccounts' resource.
        /// </summary>
        GetUserAccountResponse Get(GetUserAccount request);

        /// <summary>
        /// Defines the List request for the 'UserAccounts' resource.
        /// </summary>
        ListUserAccountsResponse Get(ListUserAccounts request);

        /// <summary>
        /// Defines the Create request for the 'UserAccounts' resource.
        /// </summary>
        CreateUserAccountResponse Post(CreateUserAccount request);

        /// <summary>
        /// Defines the Update request for the 'UserAccounts' resource.
        /// </summary>
        UpdateUserAccountResponse Put(UpdateUserAccount request);

        /// <summary>
        /// Defines the Delete request for the 'UserAccounts' resource.
        /// </summary>
        DeleteUserAccountResponse Delete(DeleteUserAccount request);

    }
}