//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Services.MessageContracts;
using ServiceStack.Web;

namespace Services.AuthZ.Workflow
{
    /// <summary>
    /// Defines the workflow manager for processing the 'AccessTokens' resource.
    /// </summary>
    internal partial interface IAccessTokensManager
    {
        /// <summary>
        /// Processes the CreateAccessToken request for the 'AccessTokens' resource.
        /// </summary>
        CreateAccessTokenResponse CreateAccessToken(IRequest request, CreateAccessToken body);

    }
}