//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Services.MessageContracts;
using ServiceStack.Web;

namespace Services.AuthZ.Workflow
{
    /// <summary>
    /// Defines the workflow manager for processing the 'ClientApplications' resource.
    /// </summary>
    internal partial interface IClientApplicationsManager
    {
        /// <summary>
        /// Processes the GetClientApplication request for the 'ClientApplications' resource.
        /// </summary>
        GetClientApplicationResponse GetClientApplication(IRequest request, GetClientApplication body);

        /// <summary>
        /// Processes the CreateClientApplication request for the 'ClientApplications' resource.
        /// </summary>
        CreateClientApplicationResponse CreateClientApplication(IRequest request, CreateClientApplication body);

        /// <summary>
        /// Processes the DeleteClientApplication request for the 'ClientApplications' resource.
        /// </summary>
        DeleteClientApplicationResponse DeleteClientApplication(IRequest request, DeleteClientApplication body);

    }
}