//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find and load certificate with subject name: &apos;{0}&apos;. The certificate does not exist in the &apos;{1}&apos; store on the &apos;{2}&apos;..
        /// </summary>
        public static string CryptoKeyProvider_FailedToFindCertificate {
            get {
                return ResourceManager.GetString("CryptoKeyProvider_FailedToFindCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read configuration for certificate &apos;{0}&apos;. You must define the value of &apos;{0}&apos; in the application configuration file..
        /// </summary>
        public static string CryptoKeyProvider_FailedToReadConfiguration {
            get {
                return ResourceManager.GetString("CryptoKeyProvider_FailedToReadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate key &apos;{0}&apos; is unknown, and not implemented..
        /// </summary>
        public static string CryptoKeyProvider_UnknownKey {
            get {
                return ResourceManager.GetString("CryptoKeyProvider_UnknownKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not a valid ID.
        /// </summary>
        public static string EntityIdValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("EntityIdValidator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be empty..
        /// </summary>
        public static string Guard_ArgumentCanNotBeEmpty {
            get {
                return ResourceManager.GetString("Guard_ArgumentCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null..
        /// </summary>
        public static string Guard_ArgumentCanNotBeNull {
            get {
                return ResourceManager.GetString("Guard_ArgumentCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be a {0}..
        /// </summary>
        public static string Guard_ArgumentTypeNotExpected {
            get {
                return ResourceManager.GetString("Guard_ArgumentTypeNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is not valid, errors are: {0}.
        /// </summary>
        public static string Guard_Validate_FailedValidation {
            get {
                return ResourceManager.GetString("Guard_Validate_FailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Funq container available to resolve validators..
        /// </summary>
        public static string Guard_Validate_NoContainer {
            get {
                return ResourceManager.GetString("Guard_Validate_NoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not a valid hash for a password.
        /// </summary>
        public static string PasswordHashValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("PasswordHashValidator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is not a field.
        /// </summary>
        public static string Reflector_ErrorNotField {
            get {
                return ResourceManager.GetString("Reflector_ErrorNotField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member access.
        /// </summary>
        public static string Reflector_ErrorNotMemberAccess {
            get {
                return ResourceManager.GetString("Reflector_ErrorNotMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a method call.
        /// </summary>
        public static string Reflector_ErrorNotMethodCall {
            get {
                return ResourceManager.GetString("Reflector_ErrorNotMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is not a property.
        /// </summary>
        public static string Reflector_ErrorNotProperty {
            get {
                return ResourceManager.GetString("Reflector_ErrorNotProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not a valid user identifier.
        /// </summary>
        public static string UserIdValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("UserIdValidator_ErrorMessage", resourceCulture);
            }
        }
    }
}
