//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.AuthZ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.AuthZ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Street&apos; of the address is not valid for a street.
        /// </summary>
        internal static string AddressValidator_InvalidAddressStreet {
            get {
                return ResourceManager.GetString("AddressValidator_InvalidAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Town&apos; of the address is not valid for a town.
        /// </summary>
        internal static string AddressValidator_InvalidAddressTown {
            get {
                return ResourceManager.GetString("AddressValidator_InvalidAddressTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client application with the identifier &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ClientApplicationsManager_ApplicationByIdentifierExists {
            get {
                return ResourceManager.GetString("ClientApplicationsManager_ApplicationByIdentifierExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client application with the name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ClientApplicationsManager_ApplicationByNameExists {
            get {
                return ResourceManager.GetString("ClientApplicationsManager_ApplicationByNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;GrantType&apos; of the request is invalid. It must be either &apos;password&apos; for a new access token, or &apos;refresh_token&apos; to refresh an existing access token.
        /// </summary>
        internal static string CreateAccessTokenValidator_InvalidGrantType {
            get {
                return ResourceManager.GetString("CreateAccessTokenValidator_InvalidGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Password&apos; for the request is not a valid password.
        /// </summary>
        internal static string CreateAccessTokenValidator_InvalidPassword {
            get {
                return ResourceManager.GetString("CreateAccessTokenValidator_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;RefreshToken&apos; for this request is not a valid refresh token.
        /// </summary>
        internal static string CreateAccessTokenValidator_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("CreateAccessTokenValidator_InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Scope&apos; for the request is not a valid scope.
        /// </summary>
        internal static string CreateAccessTokenValidator_InvalidScope {
            get {
                return ResourceManager.GetString("CreateAccessTokenValidator_InvalidScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Username&apos; for the request is not a valid username.
        /// </summary>
        internal static string CreateAccessTokenValidator_InvalidUsername {
            get {
                return ResourceManager.GetString("CreateAccessTokenValidator_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Address&apos; for the new account must be included.
        /// </summary>
        internal static string CreateUserAccountValidator_InvalidAddress {
            get {
                return ResourceManager.GetString("CreateUserAccountValidator_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Email&apos; of the new account is not a valid email.
        /// </summary>
        internal static string CreateUserAccountValidator_InvalidEmail {
            get {
                return ResourceManager.GetString("CreateUserAccountValidator_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Forenames&apos; of the new account is not a valid name or series of names.
        /// </summary>
        internal static string CreateUserAccountValidator_InvalidForenames {
            get {
                return ResourceManager.GetString("CreateUserAccountValidator_InvalidForenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Mobile Phone&apos; of the new account is not a valid phone number.
        /// </summary>
        internal static string CreateUserAccountValidator_InvalidMobilePhone {
            get {
                return ResourceManager.GetString("CreateUserAccountValidator_InvalidMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;PasswordHash&apos; for the new account is not a valid hash.
        /// </summary>
        internal static string CreateUserAccountValidator_InvalidPasswordHash {
            get {
                return ResourceManager.GetString("CreateUserAccountValidator_InvalidPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Surname&apos; of the new account is not a valid name.
        /// </summary>
        internal static string CreateUserAccountValidator_InvalidSurname {
            get {
                return ResourceManager.GetString("CreateUserAccountValidator_InvalidSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Username&apos; of the new account is not a valid username.
        /// </summary>
        internal static string CreateUserAccountValidator_InvalidUsername {
            get {
                return ResourceManager.GetString("CreateUserAccountValidator_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Email&apos; to search for is not a valid email.
        /// </summary>
        internal static string ListUserAccountsValidator_InvalidEmail {
            get {
                return ResourceManager.GetString("ListUserAccountsValidator_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Username&apos; to search for is not a valid username.
        /// </summary>
        internal static string ListUserAccountsValidator_InvalidUsername {
            get {
                return ResourceManager.GetString("ListUserAccountsValidator_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client application identifier &apos;{0}&apos; is not known.
        /// </summary>
        internal static string OAuthZServer_UnknownClientIdentifier {
            get {
                return ResourceManager.GetString("OAuthZServer_UnknownClientIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Email&apos; of the account is not a valid email.
        /// </summary>
        internal static string UpdateUserAccountValidator_InvalidEmail {
            get {
                return ResourceManager.GetString("UpdateUserAccountValidator_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Forenames&apos; of the account to update is not valid.
        /// </summary>
        internal static string UpdateUserAccountValidator_InvalidForenames {
            get {
                return ResourceManager.GetString("UpdateUserAccountValidator_InvalidForenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; of the account to update is not a valid identifier.
        /// </summary>
        internal static string UpdateUserAccountValidator_InvalidId {
            get {
                return ResourceManager.GetString("UpdateUserAccountValidator_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Mobile Phone&apos; of the account is not a valid phone number.
        /// </summary>
        internal static string UpdateUserAccountValidator_InvalidMobilePhone {
            get {
                return ResourceManager.GetString("UpdateUserAccountValidator_InvalidMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;NewPasswordHash&apos; of the account to update is invalid. It must be a hash of the user&apos;s new password..
        /// </summary>
        internal static string UpdateUserAccountValidator_InvalidNewPasswordHash {
            get {
                return ResourceManager.GetString("UpdateUserAccountValidator_InvalidNewPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;OldPasswordHash&apos; of the account to update is invalid. It must be a hash of the users existing password..
        /// </summary>
        internal static string UpdateUserAccountValidator_InvalidOldPasswordHash {
            get {
                return ResourceManager.GetString("UpdateUserAccountValidator_InvalidOldPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Surname&apos; of the account to update is not valid.
        /// </summary>
        internal static string UpdateUserAccountValidator_InvalidSurname {
            get {
                return ResourceManager.GetString("UpdateUserAccountValidator_InvalidSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user account without credentials cannot specify its role..
        /// </summary>
        internal static string UserAccountsManager_NoRolesForParticipant {
            get {
                return ResourceManager.GetString("UserAccountsManager_NoRolesForParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match. Cannot update password..
        /// </summary>
        internal static string UserAccountsManager_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("UserAccountsManager_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user account with the email &apos;{0}&apos; already exists..
        /// </summary>
        internal static string UserAccountsManager_UserAccountExistsByEmail {
            get {
                return ResourceManager.GetString("UserAccountsManager_UserAccountExistsByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user account with the username &apos;{0}&apos; already exists..
        /// </summary>
        internal static string UserAccountsManager_UserAccountExistsByUsername {
            get {
                return ResourceManager.GetString("UserAccountsManager_UserAccountExistsByUsername", resourceCulture);
            }
        }
    }
}
