//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.DataContracts
{
    /// <summary>
    /// Provides the ClientApplication DTO
    /// </summary>
    public partial class ClientApplication : IClientApplication
    {
        /// <summary>
        /// Gets or sets the identifier of the ClientApplication
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the clientidentifier
        /// </summary>
        public System.String ClientIdentifier { get; set; }

        /// <summary>
        /// Gets or sets the clientsecret
        /// </summary>
        public System.String ClientSecret { get; set; }

        /// <summary>
        /// Gets or sets the name
        /// </summary>
        public System.String Name { get; set; }

    }
}