//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;

namespace Services.DataContracts
{
    /// <summary>
    /// Defines the ClientApplication DTO
    /// </summary>
    public partial interface IClientApplication : IHasIdentifier
    {
        /// <summary>
        /// Gets or sets the clientidentifier
        /// </summary>
        System.String ClientIdentifier { get; set; }

        /// <summary>
        /// Gets or sets the clientsecret
        /// </summary>
        System.String ClientSecret { get; set; }

        /// <summary>
        /// Gets or sets the name
        /// </summary>
        System.String Name { get; set; }

    }
}