//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;

namespace Services.DataContracts
{
    /// <summary>
    /// Defines the UserAccount DTO
    /// </summary>
    public partial interface IUserAccount : IHasIdentifier
    {
        /// <summary>
        /// Gets or sets the forenames
        /// </summary>
        System.String Forenames { get; set; }

        /// <summary>
        /// Gets or sets the surname
        /// </summary>
        System.String Surname { get; set; }

        /// <summary>
        /// Gets or sets the email
        /// </summary>
        System.String Email { get; set; }

        /// <summary>
        /// Gets or sets the username
        /// </summary>
        System.String Username { get; set; }

        /// <summary>
        /// Gets or sets the passwordhash
        /// </summary>
        System.String PasswordHash { get; set; }

        /// <summary>
        /// Gets or sets the roles
        /// </summary>
        System.String Roles { get; set; }

        /// <summary>
        /// Gets or sets the mobilephone
        /// </summary>
        System.String MobilePhone { get; set; }

        /// <summary>
        /// Gets or sets the address
        /// </summary>
        DataContracts.Address Address { get; set; }

        /// <summary>
        /// Gets or sets the isregistered
        /// </summary>
        System.Boolean IsRegistered { get; set; }

    }
}