//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.DataContracts
{
    /// <summary>
    /// Provides the UserAccount DTO
    /// </summary>
    public partial class UserAccount : IUserAccount
    {
        /// <summary>
        /// Gets or sets the identifier of the UserAccount
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the forenames
        /// </summary>
        public System.String Forenames { get; set; }

        /// <summary>
        /// Gets or sets the surname
        /// </summary>
        public System.String Surname { get; set; }

        /// <summary>
        /// Gets or sets the email
        /// </summary>
        public System.String Email { get; set; }

        /// <summary>
        /// Gets or sets the username
        /// </summary>
        public System.String Username { get; set; }

        /// <summary>
        /// Gets or sets the passwordhash
        /// </summary>
        public System.String PasswordHash { get; set; }

        /// <summary>
        /// Gets or sets the roles
        /// </summary>
        public System.String Roles { get; set; }

        /// <summary>
        /// Gets or sets the mobilephone
        /// </summary>
        public System.String MobilePhone { get; set; }

        /// <summary>
        /// Gets or sets the address
        /// </summary>
        public DataContracts.Address Address { get; set; }

        /// <summary>
        /// Gets or sets the isregistered
        /// </summary>
        public System.Boolean IsRegistered { get; set; }

    }
}